<div id='main' data-scroll-offset='88'>




	<div class='stretch_full container_wrap alternate_color light_bg_color title_container'><div class='container'><h1 class='main-title entry-title'><a href='<?php echo URL;?>review/' rel='bookmark' title='Permanent Link: Reviews'  itemprop="headline" >Reviews</a></h1><div class="breadcrumb breadcrumbs avia-breadcrumbs"><div class="breadcrumb-trail" xmlns:v="http://rdf.data-vocabulary.org/#"><span class="trail-before"><span class="breadcrumb-title">You are here:</span></span> <a href="<?php echo URL;?>" title="Travel to India with Mi Consulting" rel="home" class="trail-begin">Home</a> <span class="sep">/</span> <span class="trail-end">Reviews</span></div></div></div></div><div  class='main_color container_wrap fullsize'   ><div class='container' ><main  role="main" itemprop="mainContentOfPage"  class='template-page content  av-content-full alpha units'>
	
	<div align="center">
	<h1>Our happy customer</h1>
<p>find out why our customer are so happy</p>
	</div>
	<div class='post-entry post-entry-type-page post-entry-245'><div class='entry-content-wrapper clearfix'><div  data-autoplay='1'  data-interval='5'  data-animation='fade'  data-hoverpause='1'  class='avia-testimonial-wrapper avia-grid-testimonials avia-grid-3-testimonials avia_animate_when_almost_visible '>
<section class ='avia-testimonial-row'><div class='avia-testimonial av_one_third flex_column no_margin avia-testimonial-row-1 avia-first-testimonial'  itemscope="itemscope" itemtype="https://schema.org/Person" ><div class='avia-testimonial_inner'><div class='avia-testimonial-image'  itemprop="image" ><img width="166" height="154" src="assets/img/Screen-Shot-2016-09-23-at-12.01.20.png" class="attachment-square size-square" alt="John D." /></div><div class='avia-testimonial-content '    itemscope="itemscope" itemtype="https://schema.org/CreativeWork" ><p>Great Service. MiConsulting helps me a lot. Thank you</p>
</div><div class='avia-testimonial-meta'><div class='avia-testimonial-arrow-wrap'><div class='avia-arrow'></div></div><div class='avia-testimonial-meta-mini'><strong  class='avia-testimonial-name'    itemprop="name" >John D.</strong><span  class='avia-testimonial-subtitle '    itemprop="jobTitle" >Afghanistan</span></div></div></div></div>
<div class='avia-testimonial av_one_third flex_column no_margin avia-testimonial-row-1 '  itemscope="itemscope" itemtype="https://schema.org/Person" ><div class='avia-testimonial_inner'><div class='avia-testimonial-image'  itemprop="image" ><img width="142" height="136" src="assets/img/Screen-Shot-2016-09-23-at-12.01.43.png" class="attachment-square size-square" alt="Walid F." /></div><div class='avia-testimonial-content '    itemscope="itemscope" itemtype="https://schema.org/CreativeWork" ><p>Really good Service.</p>
</div><div class='avia-testimonial-meta'><div class='avia-testimonial-arrow-wrap'><div class='avia-arrow'></div></div><div class='avia-testimonial-meta-mini'><strong  class='avia-testimonial-name'    itemprop="name" >Walid F.</strong><span  class='avia-testimonial-subtitle '    itemprop="jobTitle" >Afghanistan</span></div></div></div></div>
<div class='avia-testimonial av_one_third flex_column no_margin avia-testimonial-row-1 avia-last-testimonial'  itemscope="itemscope" itemtype="https://schema.org/Person" ><div class='avia-testimonial_inner'><div class='avia-testimonial-image'  itemprop="image" ><img width="145" height="154" src="assets/img/Screen-Shot-2016-09-23-at-12.01.52.png" class="attachment-square size-square" alt="Fred J." /></div><div class='avia-testimonial-content '    itemscope="itemscope" itemtype="https://schema.org/CreativeWork" ><p>You guys did a great job. Thanks for everything</p>
</div><div class='avia-testimonial-meta'><div class='avia-testimonial-arrow-wrap'><div class='avia-arrow'></div></div><div class='avia-testimonial-meta-mini'><strong  class='avia-testimonial-name'    itemprop="name" >Fred J.</strong><span  class='avia-testimonial-subtitle '    itemprop="jobTitle" >United States</span></div></div></div></div></section>
<section class ='avia-testimonial-row'><div class='avia-testimonial av_one_third flex_column no_margin avia-testimonial-row-2 avia-first-testimonial'  itemscope="itemscope" itemtype="https://schema.org/Person" ><div class='avia-testimonial_inner'><div class='avia-testimonial-image'  itemprop="image" ><img width="139" height="140" src="assets/img/Screen-Shot-2016-09-23-at-12.01.34.png" class="attachment-square size-square" alt="Tamira G." srcset="assets/img/Screen-Shot-2016-09-23-at-12.01.34.png 139w, assets/img/Screen-Shot-2016-09-23-at-12.01.34-80x80.png 80w, assets/img/Screen-Shot-2016-09-23-at-12.01.34-36x36.png 36w, assets/img/Screen-Shot-2016-09-23-at-12.01.34-120x120.png 120w" sizes="(max-width: 139px) 100vw, 139px" /></div><div class='avia-testimonial-content '    itemscope="itemscope" itemtype="https://schema.org/CreativeWork" ><p>Great Service. Thanks at MiConsulting</p>
</div><div class='avia-testimonial-meta'><div class='avia-testimonial-arrow-wrap'><div class='avia-arrow'></div></div><div class='avia-testimonial-meta-mini'><strong  class='avia-testimonial-name'    itemprop="name" >Tamira G.</strong><span  class='avia-testimonial-subtitle '    itemprop="jobTitle" >Afghanistan</span></div></div></div></div>
<div class='avia-testimonial av_one_third flex_column no_margin avia-testimonial-row-2 '  itemscope="itemscope" itemtype="https://schema.org/Person" ><div class='avia-testimonial_inner'><div class='avia-testimonial-image'  itemprop="image" ><img width="180" height="180" src="assets/img/PlaceHolder-180x180.png" class="attachment-square size-square" alt="Jane .D" srcset="assets/img/PlaceHolder-180x180.png 180w, assets/img/PlaceHolder-80x80.png 80w,assets/img/PlaceHolder-36x36.png 36w, assets/img/PlaceHolder-120x120.png 120w, assets/img/PlaceHolder.png 300w" sizes="(max-width: 180px) 100vw, 180px" /></div><div class='avia-testimonial-content '    itemscope="itemscope" itemtype="https://schema.org/CreativeWork" ><p>I thank MiConsulting much for there great service.</p>
</div><div class='avia-testimonial-meta'><div class='avia-testimonial-arrow-wrap'><div class='avia-arrow'></div></div><div class='avia-testimonial-meta-mini'><strong  class='avia-testimonial-name'    itemprop="name" >Jane .D</strong><span  class='avia-testimonial-subtitle '    itemprop="jobTitle" >United States</span></div></div></div></div>
</section></div>
</div></div></main><!-- close content main element --> <!-- section close by builder template -->		</div><!--end builder template--></div><!-- close default .container_wrap element -->				
<br><br><br><br><br><br>
